// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using PlcTagLib.Entities;

namespace PlcTagLib.Common.Interfaces;

public interface IPlcTagLibDbContext
{
    DbSet<MicrologixPlc> MicrologixPlcs { get; }

    DbSet<PlcTag> PlcTags { get; }
    
    DbSet<TagType> TagTypes { get; }

    Task<int> SaveChangesAsync(CancellationToken cancellationToken);
}
