// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
                                                  
namespace PlcTagLibrary.Models
{
    public partial class ListTagsByPlc
    {
        public string Name { get; set; }
        public string Gateway { get; set; }
        public string TagType { get; set; }
        public string RslinxTagName { get; set; }
        public int? Value { get; set; }
    }
}
