// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlcTagLibrary.Models;

public partial class PlcTag
{
 
    // TODO: Generate ConfiguredName from TagType and BitNumber
    // TODO: Add BitNumber to Model

    
    public int TagId { get; set; }
    public string CustomName { get; set; }
    public string RslinxTagName { get; set; }
    public int? Value { get; set; }
    public TagType TagType { get; set; }
    public int? PlcDeviceId { get; set; }

    public virtual MicrologixPlc PlcDevice { get; set; }
}

public enum TagType
{
    Output,
    Input,
    Status,
    Binary,
    Timer,
    Counter,
    Control,
    Integer,
    Float,
    Custom9,
    Custom10,
    Custom11,
    Custom12
}
